# Generated by Django 6.0.7 on 2026-08-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('coordenacao', 'Coordenação'), ('padre', 'Padre'), ('secretaria', 'Secretária'), ('liturgia', 'Liturgia'), ('tesouraria', 'Tesouraria'), ('marketing', 'Marketing')], max_length=20, verbose_name='Cargo no conselho'),
        ),
    ]
