# Generated by Django 6.0.7 on 2026-07-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('atividade', models.CharField(max_length=255, verbose_name='Atividade')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
