# Generated by Django 6.0.7 on 2026-08-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRealizado',
            fields=[
            ],
            options={
                'verbose_name': 'Evento realizado',
                'verbose_name_plural': 'Eventos realizados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('institucional.evento',),
        ),
    ]
